[build]
  publish = "."

# Redirect www to root (optional)
[[redirects]]
  from = "https://www.lochsideranch.com/*"
  to = "https://lochsideranch.com/:splat"
  status = 301
  force = true

# Security headers (basic hardening)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
